# Generated by Django 2.2.7 on 2020-01-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200102_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='names',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя'),
        ),
    ]
