# Generated by Django 2.2.7 on 2020-01-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='names',
            new_name='name',
        ),
    ]
