# Generated by Django 2.2.7 on 2020-01-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20200104_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(default=2000, verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Год',
            },
        ),
        migrations.AlterField(
            model_name='movie',
            name='ganres',
            field=models.ManyToManyField(to='movies.Ganre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.ForeignKey(default=2000, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.Year', verbose_name='Дата выхода'),
        ),
    ]
