# Generated by Django 2.2.7 on 2020-01-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20200109_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='ganre',
            name='url',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
