# Generated by Django 2.2.7 on 2020-01-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20200110_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ganre',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ganre',
            name='url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
