# Generated by Django 2.2.7 on 2020-01-10 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20200110_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieshots',
            name='description',
        ),
    ]
